---
- name: install pwquality
  package: 
    name: libpam-pwquality
    state: present

- name: reject password that contain username
  pamd:
    name: common-password
    type: password
    control: requisite
    module_path: pam_pwquality.so
    module_arguments: 'gecoscheck=1 enforce_for_root'
    state: args_present
